name: Benchmark

on:
  #  push:
  #    branches: [ main ]
  #    paths-ignore:
  #      - '**.md'
  #      - 'demo/**'
  #      - 'docs/**'
  #  pull_request:
  #    types: [ opened, synchronize, reopened ]
  #    paths-ignore:
  #      - '**.md'
  #      - 'demo/**'
  #      - 'docs/**'
  workflow_dispatch:

jobs:
  check_benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install dependencies for rendering
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            mesa-vulkan-drivers glslang-dev \
            build-essential \
            libcurl4-openssl-dev \
            libglfw3-dev \
            libuv1-dev \
            libz-dev

      - name: Check benchmark
        run: cargo bench
