name: Benchmark

on:
  #  push:
  #    branches: [ main ]
  #    paths-ignore:
  #      - '**.md'
  #      - 'demo/**'
  #      - 'docs/**'
  #  pull_request:
  #    types: [ opened, synchronize, reopened ]
  #    paths-ignore:
  #      - '**.md'
  #      - 'demo/**'
  #      - 'docs/**'
  workflow_dispatch:

jobs:
  check_benchmark:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout sources
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - run: rustup update stable && rustup default stable
      - uses: taiki-e/install-action@cc60de1d6831d7e9c4342f618ce7a5d6a9f223a4 # v2.61.6
        with: { tool: 'just' }
      - name: Install dependencies for rendering
        run: just install-dependencies

      - name: Check benchmark
        run: cargo bench
